// 门户设计专供
export { default as TodoSetting } from '@/components/VisualPortal/Todo/setting'
export { default as TaskSetting } from '@/components/VisualPortal/Task/setting'
export { default as CommonFuncSetting } from '@/components/VisualPortal/CommonFunc/setting'
export { default as TodoListSetting } from '@/components/VisualPortal/TodoList/setting'
export { default as NoticeSetting } from '@/components/VisualPortal/Notice/setting'
export { default as EmailSetting } from '@/components/VisualPortal/Email/setting'
export { default as DataBoardSetting } from '@/components/VisualPortal/DataBoard/setting'
export { default as BarChartSetting } from '@/components/VisualPortal/BarChart/setting'
export { default as AnnularChartSetting } from '@/components/VisualPortal/AnnularChart/setting'
export { default as AreaChartSetting } from '@/components/VisualPortal/AreaChart/setting'
export { default as LineChartSetting } from '@/components/VisualPortal/LineChart/setting'
export { default as PieChartSetting } from '@/components/VisualPortal/PieChart/setting'
export { default as RadarChartSetting } from '@/components/VisualPortal/RadarChart/setting'
export { default as IframeDivSetting } from '@/components/VisualPortal/IframeDiv/setting'
export { default as CarouselSetting } from '@/components/VisualPortal/Carousel/setting'
export { default as MailboxSetting } from '@/components/VisualPortal/Mailbox/setting'
export { default as SingleLoginSetting } from '@/components/VisualPortal/SingleLogin/setting'
export { default as CommonLinksSetting } from '@/components/VisualPortal/CommonLinks/setting'
export { default as DailyScheduleSetting } from '@/components/VisualPortal/DailySchedule/setting'
export { default as WeatherSetting } from '@/components/VisualPortal/Weather/setting'
export { default as AddFlowSetting } from '@/components/VisualPortal/AddFlow/setting'
export { default as DocumentSetting } from '@/components/VisualPortal/Document/setting'
export { default as NoteSetting } from '@/components/VisualPortal/Note/setting'
export { default as ContactBookSetting } from '@/components/VisualPortal/ContactBook/setting'
export { default as SinglePictureSetting } from '@/components/VisualPortal/SinglePicture/setting'
export { default as ModelQuerySetting } from '@/components/VisualPortal/ModelQuery/setting'
export { default as NewsSetting } from '@/components/VisualPortal/News/setting'
export { default as RankListSetting } from '@/components/VisualPortal/RankList/setting'
export { default as CCITAudioSetting } from '@/components/VisualPortal/CCITAudio/setting'
export { default as CCITVideoSetting } from '@/components/VisualPortal/CCITVideo/setting'
export { default as CCITMapSetting } from '@/components/VisualPortal/CCITMap/setting'
export { default as TimeLineSetting } from '@/components/VisualPortal/TimeLine/setting'
export { default as CurrentTimeSetting } from '@/components/VisualPortal/CurrentTime/setting'
export { default as DisplayFieldSetting } from '@/components/VisualPortal/DisplayField/setting'
export { default as CopyrightSetting } from '@/components/VisualPortal/Copyright/setting'
export { default as ThemeSetting } from '@/components/VisualPortal/Theme/setting'
export { default as VersionSetting } from '@/components/VisualPortal/Version/setting'
export { default as LoginFormSetting } from '@/components/VisualPortal/LoginForm/setting'
export { default as LoginTabSetting } from '@/components/VisualPortal/LoginTab/setting'

// export { default as Emaill2Setting } from '@/components/VisualPortal/Emaill2/setting'
// export { default as MeetingMattersSetting } from '@/components/VisualPortal/MeetingMatters/setting'
// export { default as ToReadSetting } from '@/components/VisualPortal/ToRead/setting'
// export { default as TodoList2Setting } from '@/components/VisualPortal/TodoList2/setting'
// export { default as ToLearnSetting } from '@/components/VisualPortal/ToLearn/setting'
// export { default as DailySchedule2Setting } from '@/components/VisualPortal/DailySchedule2/setting'
// export { default as LoginForm2Setting } from '@/components/VisualPortal/LoginForm2/setting'