// 基础控件 【左面板】
export const userComponents = [
  {
    ccitKey: 'todo',
    label: '我的待办',
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    tabs: [
      {
        title: '我的待办',
        icon: 'icon-ym icon-ym-generator-todo',
      }
    ],
    list: [],
    activeTab: 0,
    showTabsSetting: false,
    w: 12,
    h: 4,
    minW: 1,
    minH: 1,
    maxW: 24,
    maxH: 12,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false,
  },
  {
    ccitKey: 'ToLearn',
    label: '待学习事项',
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    tabs: [
      {
        title: '待学习事项',
        icon: '',
        dataInterface: '',
      }
    ],
    list: [],
    activeTab: 0,
    showTabsSetting: false,
    w: 12,
    h: 4,
    minW: 1,
    minH: 1,
    maxW: 24,
    maxH: 12,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false
  },
  {
    ccitKey: 'ToRead',
    label: '待阅事项',
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    tabs: [
      {
        title: '待阅事项',
        icon: '',
        dataInterface: '',
      }
    ],
    list: [],
    activeTab: 0,
    showTabsSetting: false,
    w: 12,
    h: 4,
    minW: 1,
    minH: 1,
    maxW: 24,
    maxH: 12,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false
  },
  {
    ccitKey: 'MeetingMatters',
    label: '会议事项',
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    tabs: [
      {
        title: '会议事项',
        icon: '',
        dataInterface: '',
      }
    ],
    list: [],
    activeTab: 0,
    showTabsSetting: false,
    w: 12,
    h: 4,
    minW: 1,
    minH: 1,
    maxW: 24,
    maxH: 12,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false
  },
  {

    ccitKey: 'EmployeeSelfService',
    label: '员工自助',
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    tabs: [
      {
        title: '员工自助',
        icon: '',
      }
    ],
    showTabsSetting: false,
    list: [
      { fullName: "功能设计", id: "85cd7bca426e49ce83a061bf461b1447", urlAddress: "OnlineDev/WebDesign", icon: "icon-ym icon-ym-webDesign", iconBackgroundColor: "#FF3B3B" },
      { fullName: "流程设计", id: "fe0150960dd542ec9328067e4495074b", urlAddress: "WorkFlow/FlowEngine", icon: "icon-ym icon-ym-flowDesign", iconBackgroundColor: "#7B1AE1" },
      { fullName: "权限管理", id: "9057d797550e4457b7ddf2456ce45882", urlAddress: "Permission/Authorize", icon: "icon-ym icon-ym-authorize", iconBackgroundColor: "#1890FF" },
      { fullName: "报表设计", id: "c7159f97177b420d9fc8ec8c74ae541b", urlAddress: "OnlineDev/DataReport", icon: "icon-ym icon-ym-reportDesign", iconBackgroundColor: "#F68900" },
      { fullName: "门户设计", id: "232d7226f00446d882e1e1bd999f7b2d", urlAddress: "OnlineDev/VisualPortal", icon: "icon-ym icon-ym-portalDesign", iconBackgroundColor: "#33B932" }
    ],
    w: 12,
    h: 4,
    minW: 1,
    minH: 1,
    maxW: 24,
    maxH: 12,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false
  },
  {
    label: '我的任务',
    ccitKey: 'task',
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    tabs: [
      {
        title: '我的任务',
        icon: 'icon-ym icon-ym-generator-menu',
      }
    ],
    showTabsSetting: false,
    w: 6,
    h: 7,
    minW: 1,
    minH: 1,
    maxW: 24,
    maxH: 12,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false
  },
  {
    ccitKey: 'commonFunc',
    label: '常用功能',
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    tabs: [
      {
        title: '常用功能',
        icon: 'icon-ym icon-ym-generator-function',
      }
    ],
    showTabsSetting: false,
    list: [
      { fullName: "功能设计", id: "85cd7bca426e49ce83a061bf461b1447", urlAddress: "OnlineDev/WebDesign", icon: "icon-ym icon-ym-webDesign", iconBackgroundColor: "#FF3B3B" },
      { fullName: "流程设计", id: "fe0150960dd542ec9328067e4495074b", urlAddress: "WorkFlow/FlowEngine", icon: "icon-ym icon-ym-flowDesign", iconBackgroundColor: "#7B1AE1" },
      { fullName: "权限管理", id: "9057d797550e4457b7ddf2456ce45882", urlAddress: "Permission/Authorize", icon: "icon-ym icon-ym-authorize", iconBackgroundColor: "#1890FF" },
      { fullName: "报表设计", id: "c7159f97177b420d9fc8ec8c74ae541b", urlAddress: "OnlineDev/DataReport", icon: "icon-ym icon-ym-reportDesign", iconBackgroundColor: "#F68900" },
      { fullName: "门户设计", id: "232d7226f00446d882e1e1bd999f7b2d", urlAddress: "OnlineDev/VisualPortal", icon: "icon-ym icon-ym-portalDesign", iconBackgroundColor: "#33B932" }
    ],
    w: 12,
    h: 4,
    minW: 1,
    minH: 1,
    maxW: 24,
    maxH: 12,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false
  },
  {
    ccitKey: 'notice',
    label: '公告通知',
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    tabs: [
      {
        title: '公告通知',
        icon: 'icon-ym icon-ym-generator-notice',
      }
    ],
    showTabsSetting: false,
    showHeader: false,
    list: [
      { label: '标题', prop: 'fullName', selection: true },
      { label: '发布人', prop: 'creator', selection: true },
      { label: '发布时间', prop: 'publishTime', selection: true }
    ],
    w: 8,
    h: 7,
    minW: 1,
    minH: 1,
    maxW: 24,
    maxH: 12,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false
  },
  {
    ccitKey: 'email',
    label: '未读邮件',
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    tabs: [
      {
        title: '未读邮件',
        icon: 'icon-ym icon-ym-generator-email',
      }
    ],
    showTabsSetting: false,
    w: 12,
    h: 7,
    minW: 1,
    minH: 1,
    maxW: 24,
    maxH: 12,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false
  },
  {
    ccitKey: 'todoList',
    label: '待办事项',
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    tabs: [
      {
        title: '待办事项',
        icon: 'icon-ym icon-ym-generator-todolist',
      }
    ],
    showTabsSetting: false,
    showHeader: false,
    showPagination: false,
    innerTabs: [
      {
        label: '待办', name: 'sys', show: true
      },
      { label: '已办', name: 'outer', show: true }
    ],
    showOuter: true,
    pageSize: 5,
    list: [
      { label: '标题', prop: 'fullName', selection: true },
      { label: '紧急程度', prop: 'flowUrgent', selection: true },
      { label: '发起时间', prop: 'startTime', selection: true },
      { label: '流程状态', prop: 'status', selection: true },
      { label: '接收时间', prop: 'creatorTime', selection: true }
    ],
    w: 12,
    h: 7,
    minW: 1,
    minH: 1,
    maxW: 24,
    maxH: 12,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false
  },
  {
    ccitKey: 'carousel',
    label: '图片轮播',
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    tabs: [
      {
        title: '图片轮播',
        icon: 'ym-custom ym-custom-numeric--box-multiple-outline',
      }
    ],
    showTabsSetting: false,
    list: [],
    config: { interval: 3000, type: 'card', arrow: 'always', indicatorPosition: 'none', autoplay: 'false' },
    w: 24,
    h: 5,
    minW: 1,
    minH: 1,
    maxW: 24,
    maxH: 12,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false
  },
  {
    ccitKey: 'mailbox',
    label: '我的邮箱',
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    tabs: [
      {
        title: '我的邮箱',
        icon: 'ym-custom ym-custom-email-outline',

      }
    ],
    showTabsSetting: false,
    list: [
      { name: '写信', icon: 'icon-ym icon-ym-extend-pencil', type: 'write' },
      { name: '通讯录', icon: 'icon-ym icon-ym-generator-jobs', type: 'loadIn' },
      { name: '进入邮箱', icon: 'el-icon-right', type: 'loadIn' },
    ],
    w: 16,
    h: 6,
    minW: 1,
    minH: 1,
    maxW: 24,
    maxH: 12,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false
  },
  {
    ccitKey: 'dailySchedule',
    label: '我的事项',
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    tabs: [
      {
        title: '我的事项',
        icon: 'ym-custom ym-custom-calendar-check',

      }
    ],
    showTabsSetting: false,
    showBtn: false,
    reverse: false,
    isCollapes: true,
    scheduleType: 'timeline',
    showAdd: true,
    showWeather: true,
    w: 6,
    h: 12,
    minW: 1,
    minH: 1,
    maxW: 24,
    maxH: 24,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false
  },
  {
    ccitKey: 'weather',
    label: '天气预报',
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    tabs: [
      {
        title: '天气预报',
        icon: 'ym-custom ym-custom-weather-cloudy',
      }
    ],
    showTabsSetting: false,
    mode: 'standard',
    w: 12,
    h: 3,
    minW: 1,
    minH: 1,
    maxW: 24,
    maxH: 12,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false
  },
  {
    ccitKey: 'contactBook',
    label: '通讯录',
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    tabs: [
      {
        title: '通讯录',
        icon: 'ym-custom ym-custom-cellphone-link',

      }
    ],
    showTabsSetting: false,
    showHeader: true,
    showPagination: true,
    list: [
      { label: '账号', prop: 'account', selection: true },
      { label: '姓名', prop: 'realName', selection: true },
      { label: '性别', prop: 'gender', selection: true },
      { label: '手机', prop: 'mobilePhone', selection: true },
      { label: '部门', prop: 'department', selection: true },
      { label: '岗位', prop: 'position', selection: true },
    ],
    w: 16,
    h: 6,
    minW: 1,
    minH: 1,
    maxW: 24,
    maxH: 12,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false
  },
  {
    ccitKey: 'currentTime',
    label: '当前时间',
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    tabs: [
      {
        title: '当前时间',
        icon: 'icon-ym icon-ym-generator-time',
      }
    ],
    showTabsSetting: false,
    format: 'YYYY年MM月DD日 HH:mm:ss',
    color: '#3A8AD1',
    fontSize: 18,
    fontFamily: 'PingFang SC',
    showWeek: true,
    showClock: true,
    css: '',
    w: 8,
    h: 4,
    minW: 2,
    minH: 1,
    maxW: 18,
    maxH: 12,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false
  },
  {
    ccitKey: 'news',
    label: '企业新闻',
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    tabs: [
      {
        title: '企业新闻',
        icon: 'ym-custom ym-custom-newspaper',
      }
    ],
    showTabsSetting: false,
    categoryCode: '',
    columns: [{
      label: '标题', prop: 'title',
      selection: true,
    },
    {
      label: '所属栏目', prop: 'categoryName',
      selection: false,
    },
    {
      label: '创建人', prop: 'createBy',
      selection: false,
    },
    {
      label: '创建时间', prop: 'createDate',
      selection: true,
      width: 120
    }],
    showHeader: false,
    showCarousel: true,
    showRecommend: true,
    w: 12,
    h: 7,
    minW: 3,
    minH: 7,
    maxW: 24,
    maxH: 16,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false
  },
]
