// 门户设计专供
export { default as Todo } from '@/components/VisualPortal/Todo'
export { default as Task } from '@/components/VisualPortal/Task'
export { default as CommonFunc } from '@/components/VisualPortal/CommonFunc'
export { default as TodoList } from '@/components/VisualPortal/TodoList'
export { default as Notice } from '@/components/VisualPortal/Notice'
export { default as Email } from '@/components/VisualPortal/Email'
export { default as DataBoard } from '@/components/VisualPortal/DataBoard'
export { default as BarChart } from '@/components/VisualPortal/BarChart'
export { default as AnnularChart } from '@/components/VisualPortal/AnnularChart'
export { default as AreaChart } from '@/components/VisualPortal/AreaChart'
export { default as LineChart } from '@/components/VisualPortal/LineChart'
export { default as PieChart } from '@/components/VisualPortal/PieChart'
export { default as RadarChart } from '@/components/VisualPortal/RadarChart'
export { default as IframeDiv } from '@/components/VisualPortal/IframeDiv'
export { default as Carousel } from '@/components/VisualPortal/Carousel'
export { default as Mailbox } from '@/components/VisualPortal/Mailbox'
export { default as SingleLogin } from '@/components/VisualPortal/SingleLogin'
export { default as CommonLinks } from '@/components/VisualPortal/CommonLinks'
export { default as DailySchedule } from '@/components/VisualPortal/DailySchedule'
export { default as Weather } from '@/components/VisualPortal/Weather'
export { default as AddFlow } from '@/components/VisualPortal/AddFlow'
export { default as Document } from '@/components/VisualPortal/Document'
export { default as Note } from '@/components/VisualPortal/Note'
export { default as ContactBook } from '@/components/VisualPortal/ContactBook'
export { default as ModelQuery } from '@/components/VisualPortal/ModelQuery'
export { default as News } from '@/components/VisualPortal/News'
export { default as RankList } from '@/components/VisualPortal/RankList'
export { default as CCITAudio } from '@/components/VisualPortal/CCITAudio'
export { default as CCITVideo } from '@/components/VisualPortal/CCITVideo'
export { default as CCITMap } from '@/components/VisualPortal/CCITMap'
export { default as TimeLine } from '@/components/VisualPortal/TimeLine'
export { default as CurrentTime } from '@/components/VisualPortal/CurrentTime'
export { default as DisplayField } from '@/components/VisualPortal/DisplayField'
export { default as SinglePicture } from '@/components/VisualPortal/SinglePicture'
export { default as Copyright } from '@/components/VisualPortal/Copyright'
export { default as Theme } from '@/components/VisualPortal/Theme'
export { default as LoginForm } from '@/components/VisualPortal/LoginForm'
export { default as Version } from '@/components/VisualPortal/Version'
export { default as LoginTab } from '@/components/VisualPortal/LoginTab'
// export { default as TodoList2 } from '@/components/VisualPortal/TodoList2'
// export { default as Emaill2 } from '@/components/VisualPortal/Emaill2'
// export { default as MeetingMatters } from '@/components/VisualPortal/MeetingMatters'
// export { default as ToLearn } from '@/components/VisualPortal/ToLearn'
// export { default as ToRead } from '@/components/VisualPortal/ToRead'
// export { default as EmployeeSelfService } from '@/components/VisualPortal/EmployeeSelfService'

//春节的模块（暂时）
// export { default as TodoList3 } from '@/components/VisualPortal/TodoList3'
// export { default as Emaill3 } from '@/components/VisualPortal/Emaill3'
// export { default as ToRead3 } from '@/components/VisualPortal/ToRead3'
// export { default as EmployeeSelfService3 } from '@/components/VisualPortal/EmployeeSelfService3'
// export { default as DailySchedule2 } from '@/components/VisualPortal/DailySchedule2'
export { default as LoginForm2 } from '@/components/VisualPortal/LoginForm2'

// 国风门户样式模块（暂时）
// export { default as ChineseTodoList } from '@/components/VisualPortal/ChineseTodoList'
// export { default as ChineseEmaill } from '@/components/VisualPortal/ChineseEmaill'
// export { default as ChineseToRead } from '@/components/VisualPortal/ChineseToRead'
// export { default as ChineseEmployeeSelfService } from '@/components/VisualPortal/ChineseEmployeeSelfService'
